import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'org.jetbrains.kotlin.jvm' version '2.3.21'
    id 'maven-publish'
}

version = project.mod_version
group = project.mod_group

base {
    archivesName = project.mod_id
}

repositories {
    maven {
        name = 'Fabric'
        url = 'https://maven.fabricmc.net/'
    }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    implementation "net.fabricmc:fabric-language-kotlin:${project.fabric_kotlin_version}"
}

tasks.named('processResources', ProcessResources).configure {
    def replaceProperties = [
            version              : project.version,
            minecraft_version    : project.minecraft_version,
            loader_version       : project.loader_version,
            fabric_api_version   : project.fabric_api_version,
            fabric_kotlin_version: project.fabric_kotlin_version,
            mod_id               : project.mod_id,
            mod_name             : project.mod_name,
            mod_license          : project.mod_license,
            mod_author           : project.mod_author,
            mod_description      : project.mod_description
    ]

    inputs.properties replaceProperties

    filesMatching('fabric.mod.json') {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}

tasks.withType(KotlinCompile).configureEach {
    compilerOptions.jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_25)
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
    withSourcesJar()
}
