org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
kotlin.code.style=official

# Minecraft / Fabric
minecraft_version=26.1
loader_version=0.18.4
fabric_api_version=0.145.1+26.1
fabric_kotlin_version=1.13.11+kotlin.2.3.21

# Mod metadata
mod_id=better_health_indicator
mod_name=Better Health Indicator
mod_version=0.1.0
mod_group=dev.wenjiazhen
mod_author=wenjiazhen
mod_description=A cute client-side Fabric mod for displaying better Minecraft health bars.
