modLoader="kotlinforforge"
loaderVersion="${kotlin_for_forge_loader_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
logoFile="assets/better_health_indicator/icon.png"
authors="${mod_author}"
description='''${mod_description}'''

[[mixins]]
config="better_health_indicator.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="cloth_config"
type="optional"
versionRange="[${cloth_config_version},)"
ordering="AFTER"
side="CLIENT"
