minecraft_version=1.21.11
minecraft_version_range=[1.21.11]
resource_pack_format=75
resource_pack_format_minor=0
java_version=21
forge_version=61.1.9
forge_version_range=[61.1.9,)
forge_loader_range=[61,)
kotlin_for_forge_version=6.0.0
kotlin_for_forge_loader_range=[6.0,7)
kotlin.stdlib.default.dependency=false
cloth_config_version=21.11.153
