minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
resource_pack_format=84
resource_pack_format_minor=0
java_version=25
bytecode_java_version=21
forge_version=64.0.12
forge_version_range=[64.0.12,)
forge_loader_range=[64,)
kotlin_for_forge_version=6.2.0
kotlin_for_forge_loader_range=[6.2,7)
kotlin.stdlib.default.dependency=false
cloth_config_version=26.1.154
